---

# Defines when this workflow runs, a trigger event
on: [push]

# We define the collection of jobs this workflow will run
# Run in parallalel by default
jobs:
  # Deines a job named test-lint
  test-lint:
    name: Test and Lint # Human readable name
    runs-on: ubuntu-20.04 # Specifies the environment for the job
    #Define the sequence of tasks that will be executed in this job
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # Uses a pre-built action
        with: # Specifies parameters to pass to the action
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        # Uses GitHub's checkout action to clone your repository code
        uses: actions/checkout@v2 # This makes your code available to subsequent steps
        # Names the step that will run your Django tests
      - name: Tests
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"